const $=(s)=>document.querySelector(s);const $$=(s)=>[...document.querySelectorAll(s)];
const toast=(message)=>{const el=$('#toast');el.querySelector('p').textContent=message;el.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>el.classList.remove('show'),2200)};
$$('.chip').forEach(chip=>chip.addEventListener('click',()=>chip.classList.toggle('active')));
$$('.heart').forEach(heart=>heart.addEventListener('click',(e)=>{e.stopPropagation();heart.classList.toggle('active');heart.textContent=heart.classList.contains('active')?'♥':'♡';toast(heart.classList.contains('active')?'お気に入りに保存しました':'お気に入りから外しました')}));
const modal=$('#modal');function openModal(){modal.classList.add('open');modal.setAttribute('aria-hidden','false');$('#modalAction').style.display='none';$('.loading').style.display='flex';$('#modalTitle').textContent='旅をつくっています';$('#modalText').textContent='あなたの「好き」を組み合わせて、3つのプランを考えています。';setTimeout(()=>{$('.loading').style.display='none';$('#modalTitle').textContent='3つの旅ができました';$('#modalText').textContent='京都の定番、ローカル、グルメ。今の気分に合う旅を選んでください。';$('#modalAction').style.display='flex'},1400)}
$('#generateBtn').addEventListener('click',openModal);$('#mobilePlan').addEventListener('click',()=>{$('#planner').scrollIntoView({behavior:'smooth'});setTimeout(()=>$('#destination').focus(),500)});$('#modalClose').addEventListener('click',()=>modal.classList.remove('open'));$('.modal-backdrop').addEventListener('click',()=>modal.classList.remove('open'));$('#modalAction').addEventListener('click',()=>{modal.classList.remove('open');$('#plans').scrollIntoView({behavior:'smooth'})});
const places=['京都','金沢','鎌倉','尾道','高山'];let placeIndex=0;$('#randomPlace').addEventListener('click',()=>{$('#destination').value=places[++placeIndex%places.length];toast('行き先候補を更新しました')});
let people=2;$('#peopleBtn').addEventListener('click',()=>{people=people===6?1:people+1;$('#peopleLabel').textContent=`${people}人`});
const dates=['7月18日 — 20日','8月8日 — 10日','9月21日 — 23日'];let dateI=0;$('#dateBtn').addEventListener('click',()=>{$('#dateLabel').textContent=dates[++dateI%dates.length]});
$$('.choose-plan').forEach(btn=>btn.addEventListener('click',()=>{$('#itinerary').scrollIntoView({behavior:'smooth'});toast(`${btn.closest('.plan-card').dataset.plan}プランを選びました`)}));
$('#regenerateBtn').addEventListener('click',()=>$('#planner').scrollIntoView({behavior:'smooth'}));
const spots=[{title:'夕暮れの二年坂',desc:'灯りがともる、少し前。\nいちばん美しい時間。'},{title:'朝の錦市場',desc:'湯気と声が行き交う、\n京都のおいしい台所。'},{title:'鴨川でひと休み',desc:'旅の途中に、何もしない\n贅沢な30分を。'}];let spot=0;function changeSpot(step){spot=(spot+step+spots.length)%spots.length;$('#videoPhone').animate([{opacity:.4,transform:'translateX(12px)'},{opacity:1,transform:'translateX(0)'}],{duration:320});$('#spotTitle').textContent=spots[spot].title;$('#spotDesc').innerHTML=spots[spot].desc.replace('\n','<br>')}
$('#nextSpot').addEventListener('click',()=>changeSpot(1));$('#prevSpot').addEventListener('click',()=>changeSpot(-1));$('#addSpotBtn').addEventListener('click',()=>toast(`${spots[spot].title}を旅程に追加しました`));
let playing=false;$('#playBtn').addEventListener('click',()=>{playing=!playing;$('#playBtn').textContent=playing?'❚❚':'▶';toast(playing?'スポット動画を再生中':'一時停止しました')});
$$('.day-tabs button').forEach((btn,i)=>btn.addEventListener('click',()=>{$$('.day-tabs button').forEach(b=>b.classList.remove('active'));btn.classList.add('active');$('.schedule-head small').textContent=`7月${18+i}日（${['土','日','月'][i]}）`;toast(`DAY ${i+1} の旅程を表示しました`)}));
$('#navBtn').addEventListener('click',()=>toast('清水寺までのナビを開始します'));$('#detailBtn').addEventListener('click',()=>toast('旅程の詳細を開きました'));$('#shareBtn').addEventListener('click',()=>toast('共有リンクをコピーしました'));
$$('.desktop-nav a,.mobile-nav a').forEach(a=>a.addEventListener('click',()=>{$$('.desktop-nav a,.mobile-nav a').forEach(x=>x.classList.remove('active'));a.classList.add('active')}));
